name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Or your preferred runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python, pip, and Sphinx
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install Sphinx
          pip install sphinx piccolo_theme  # Install the Piccolo theme

      - name: Clean build directory (optional)
        run: |
          cd docs
          rm -rf _build  # This removes any cached build artifacts

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          publish_dir: ./docs/_build/html
